# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 012cf34ac86cd4229703d62c3692ea75ea954f32ff5e0abde3c2ee02cd81ebcfae44803458923520802e44e87478d3eba5cacbe76b91801fc11e11f9267a18a7

test:
  secret_key_base: 6125938ede9ba4e2b1ec4def76658c7ebd4686cd45fd30f27c5ca1aa89d41ecb40c9f6e3efaa9b28c7c8722532cabd8922257abe22d8f937d0569ed8a8234b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
